name: MAME-libretro Windows x86_64

on:
  push:
    branches:
      - master

jobs:
  Windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
    - name: Setup MINGW64
      uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
    - name: Install needed packages
      run: msys2do pacman -S --noconfirm --disable-download-timeout --needed wget git make mingw-w64-x86_64-binutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-pkg-config mingw-w64-x86_64-python2 zip p7zip
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build libretro mame core
      run: |
        msys2do make -f Makefile.libretro -j8
        strip.exe -s mame_libretro.dll
        msys2do zip -9 mame_libretro.dll.zip mame_libretro.dll
        msys2do sha256sum mame_libretro.dll.zip > mame_libretro.dll.zip.sha256
    - name: Create new release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: Windows_64-bit
        prerelease: false
        title: Windows x86_64
        files: |
          mame_libretro.dll.zip
          mame_libretro.dll.zip.sha256
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: mame_libretro.dll.zip
        path: mame_libretro.dll.zip


